---
- name: Test Ansible-playbook
  hosts: all
  become: yes
  
  tasks:
    - name: Pinging server
      ping:

    - name: Installing Apache2
      apt:
        name: tree
        state: present
    
    - name: Coping local files to server
      copy:
        src: /etc/ansible/sample-file-to-copy.txt
        dest: /home/ansible
